### ISSUE TITLE
Coil always renders SVGs to bitmaps

### ISSUE THREAD

**Issue by colinrtwhite** [chrisbanes/accompanist#10]
It says in the Coil readme that [SVGs will always result in a rasterized bitmap](https://github.com/chrisbanes/accompanist/blob/master/coil/README.md#limitations). Coil actually [always returns SVGs as `BitmapDrawable`s](https://github.com/coil-kt/coil/blob/master/coil-svg/src/main/java/coil/decode/SvgDecoder.kt#L83) instead of vectors for performance reasons. Maybe it should say that GIFs will always be rendered to the first frame instead of animating instead?

**Comment by chrisbanes** [comment]
Woops, I'll fix!
