### ISSUE TITLE
CoilImageWithCrossfade scale animation issue

### ISSUE THREAD

**Issue by denis-ismailaj** [chrisbanes/accompanist#102]
Case: 
Using `CoilImageWithCrossfade` with an high resolution image and `ContentScale.FillWidth`.

Issue:
The animation happens before the image is scaled, so at first you only see the top-left part of the image then it abruptly scales itself.

**Comment by chrisbanes** [comment]
Just tried this on top-of-tree and I can't recreate (loading a 3200x3200px image in a 200dp x 200dp image). The next release is going in roughly a hour, so I'm hoping this will be fixed in the next release 🤞

**Comment by denis-ismailaj** [comment]
After upgrading to `v0.3.0`, and using `CoilImage` with `fadeIn = true`, this works perfectly!

Issue closed.
