### ISSUE TITLE
Desktop Compose support

### ISSUE THREAD

**Issue by joreilly** [chrisbanes/accompanist#136]
Checking just in case there's any plans to create version that works with new Compose for Desktop release (or has this dependency on running on Android)?

**Comment by chrisbanes** [comment]
Likely not unfortunately. All of the image loading libraries we support have a dependency on Android.

I wonder if Coil could be refactored with a Kotlin only base lib? @colinrtwhite

The new insets support is very dependent on Android too.

**Comment by colinrtwhite** [comment]
Hmm I wouldn't rule it out entirely, but it probably not. Off the top of my head here are some hurdles:

- Okio and Coroutines are multiplatform, but OkHttp isn't. Not sure if they plan to support multiplatform, but if not we would have to add hooks to use other networking libraries (and maybe write our own disk cache).
- Coil is very coupled with `Bitmap`. I'm not sure if `BufferedImage` or another Swing class supports everything we use.
- Coil is very coupled with `BitmapFactory`. Supporting all of Coil's functionality using Swing's APIs would be a lot of effort.
- There's probably more as well...

**Comment by chrisbanes** [comment]
Makes sense to me @colinrtwhite. Marking this as 'wontfix' for now.

**Comment by outadoc** [comment]
I'm experimenting with Compose Desktop, and thinking of using `accompanist-insets` in the common code. For a lib like this one, it could make sense to provide no-ops for platforms other than Android, e.g. a function like `Modifier.navigationBarsPadding()` provides `0.dp` on desktop.

There might be issues I haven't considered but it would be very useful not to have to provide a multiplatform wrapper myself.

**Comment by chrisbanes** [comment]
I’m not sure this actually possible right now. Both the Android and Desktop targets would be `jvm` and I think there can be only one in a KMP library.

Happy to be proven wrong though.

**Comment by mcpiroman** [comment]
What about simple components like `flowlayout` which don't use any dependency on android? For now I have to copy paste the code into my compose-desktop project.

**Comment by mcpiroman** [comment]
Ok, I see there is #393
