### ISSUE TITLE
Support for WindowInsetsAnimation

### ISSUE THREAD

**Issue by sjmueller** [chrisbanes/accompanist#140]
With the introduction of Insets to accompanist, are there any plans to add support for `WindowInsetsAnimation`? This allows fine grain control and coordination of the keyboard animation (as described in [this article](https://proandroiddev.com/exploring-windowinsets-on-android-11-a80cf8fe19be)):

<img src="https://user-images.githubusercontent.com/29085/98899402-5bc68b00-2464-11eb-9e24-9ee92b50a35d.gif" width="200" />

I found some code that shows how to add the callback within MainActivity, but it's not a jetpack compose app and so the `content` property isn't available:
https://github.com/siyehua/WindowInsetsAnimation/blob/a31ea8f5d73d29fcfcaa8f7386b66ed7297f8aea/app/src/main/java/com/example/myapplication/MainActivity.kt

**Comment by chrisbanes** [comment]
Hi Sam, yep it's something I'm already thinking about. Stay tuned.

**Comment by chrisbanes** [comment]
This was added [0.4.0](https://github.com/chrisbanes/accompanist/releases/tag/v0.4.0).
