### ISSUE TITLE
CoilImage: ImageState is Empty (briefly) before the image loads.

### ISSUE THREAD

**Issue by Bradleycorn** [chrisbanes/accompanist#141]
When using the "content version" of the `CoilImage` composable, it is composed in the "empty" state briefly before the request starts (and it then gets recomposed in the "loading" state). This **could** cause a brief "flash" of the empty state, if the device is slow. I haven't seen it on a physical device, but if you add a log message in the content composable for the Empty state, you will see it. One way that I HAVE been able to see it, is to create a `@Preview` for the below composable, and then in Android Studio click the "Deploy Preview" button to deploy the preview to an emulator. When the preview app loads on the emulator, you can see the brief flash of the Empty State before the Loading state. For example:

```
@Composable
fun MyImage() {
    CoilImage(
        data = "https://picsum.photos/300/300",
    ) { imageState ->
        when (imageState) {
            is ImageLoadState.Success -> {
                MaterialLoadingImage(
                    result = imageState,
                    fadeInEnabled = true,
                    fadeInDurationMs = 600,
                )
            }
            is ImageLoadState.Error -> /* TODO */
            ImageLoadState.Loading -> Text("Loading...")
            ImageLoadState.Empty -> {
                  Log.d(TAG, "COIL IMAGE IS EMPTY")
                  Text("⚠️ EMPTY! ⚠️")
            }
        }
    }
}
```

When the `MyImage` composable is called the UI will go through the following states:

1. ⚠️ EMPTY! ⚠️ (You won't typically see this on a device, but if you check the LogCat, you will find the "COIL IMAGE IS EMPTY" message logged there).
2. Loading...
3. ![image](https://user-images.githubusercontent.com/4521694/99001584-1c05af00-2509-11eb-9f1d-41be541d17ed.png)

It seems like it should go directly to the "Loading" state, and then to the Success (show the image) state, and skip the Empty state all together in this case.

**Comment by chrisbanes** [comment]
I was initially thinking that we could change the internal loading logic to add a debounce on the `Loading` state, but the more I think about this, the more than feels like a UI thing.

The way I'm thinking about this is that we wrap the `loading()` content with something like this:

``` kotlin
@Composable
fun WithDelay(
    delayMs: Long,
    content: @Composable () -> Unit
) {
    var visible by remember { mutableStateOf(false) }

    LaunchedEffect(Unit) {
        delay(delayMs)
        visible = true
    }

    if (visible) content()
}
```

You can then do:

``` kotlin
CoilImage(
    // ...
    loading = {
        // choose whatever delay works, 500ms is a good initial value
        WithDelay(500) {
            Text("Loading...")
        }
    }
)
```

This matches the behavior of [`ContentLoadingProgressBar`](https://developer.android.com/reference/androidx/core/widget/ContentLoadingProgressBar), and feels right.

I haven't quite whether to bake this into the 'simple' `CoilImage` etc yet. I don't really want to add yet-another-parameter to control the delay, and the integration is pretty simple to do in clients.

**Comment by Bradleycorn** [comment]
I wired that up, and it certainly works. Though for the scenario I described, you'd want to to use `withDelay` in the `Empty` state instead of the `Loading` state. it's a flash of the `Empty` state that I'm trying to eliminate. But, it could be useful in the `Loading` state as well. In cases where the image gets loaded fast, you could prevent a "flash" of the `Loading` state composable. 

That also lends to the idea of NOT adding the delay as a parameter on the simple `CoilImage` composable. Different use cases might require delays on different states. As you mentioned, it's simple to wire up. It took me 2 minutes, and I even had to roll my own `withDelay` composable. If a client wants/needs a delay on a certain state, it's easy to setup.

**Comment by chrisbanes** [comment]
Ahhh, I misread the scenario 🤔

This makes me think that the `Empty` state is actually useless, since we always transition to `Loading` after the first composition + layout. The thrashing has no benefit.

One thought is to merge those into a single `Pending` state.

**Comment by Bradleycorn** [comment]
yeah, when I looked at it originally, I kind of wandered if you could just initialize it in the `Loading` state. Merging the two might do the trick. One thing the `Empty` state IS useful for is supplying a drawable resource to use for `@Preview` composables in Android Studio. That's what led me down this rabbit hole in the first place. It might be useful to keep the `Empty` state around, but only use it in a case where the `data` parameter is null or otherwise empty.

**Comment by chrisbanes** [comment]
Thanks for the info! I think I'm going to proceed with the merging to a new `Pending` state.

Can you attach an example of what you're doing for `@Preview`s? I think we can fix that separately rather than relying on `Empty`.

**Comment by Bradleycorn** [comment]
As a learning effort, I'm building a pretty basic app to consume a feed from a blog that I read and show posts, very similar to the JetNews sample app.  The top post in the list on the home screen is "featured" and shows an image. My Composable for the top post looks like this:
```
@Composable
fun FeaturedPost(post: Post) {
    Column {
        PostImage(post.imageUrl)
        PostItem(post)
    }
}

@Composable
fun PostImage(url: String, modifier: Modifier = Modifier.fillMaxWidth().aspectRatio(1.78F)) {
    CoilImage(
        data = url,
        modifier = modifier) { imageState ->
        when (imageState) {
            is ImageLoadState.Success -> {
                MaterialLoadingImage(
                    result = imageState,
                    fadeInEnabled = true,
                    fadeInDurationMs = 600,
                    contentScale = ContentScale.Crop
                )
            }
            is sImageLoadState.Empty -> {
                //  Use this image in the Preview in Android Studio
                Image(asset = vectorResource(id = R.drawable.ic_uk_logo),
                    modifier = Modifier.fillMaxSize().padding(16.dp),
                    contentScale = ContentScale.Fit)
            }
        }
    }
}
```

The `Post` model (instances of which are created from the response of an API call) contains several fields, one of them being an image url:
```
data class Post(url: String, imageUrl: String, title: String, content: String) // etc, etc
```
To Preview a featured post, I create a mock Post, and call the FeaturedPost composable:
```
@Preview("Featured Post")
@Composable
fun PreviewPost() {
    val post = Post(
        url = "postUrl",
        image = "https://kentuckysportsradio.com/wp-content/uploads/2018/09/MSU-8843.jpg",
        title = "Featured Post Title",
        description = "The post preview is a a short description of the content that is in the main post",
        author = "Brad Ball",
        postDate = Date().time,
        content = "Main post content")

    ThemedPreview() {
        FeaturedPost(post)
    }
}
```

**Comment by chrisbanes** [comment]
Thanks! Yeah, I think we can do better here when in preview.

**Comment by chrisbanes** [comment]
Open #150 for this.
