### ISSUE TITLE
No Such Field Error

### ISSUE THREAD

**Issue by jonneymendoza** [chrisbanes/accompanist#143]
Hiya i am getting the follow error when using CoilImage

```java.lang.NoSuchFieldError: No field Companion of type Landroidx/compose/runtime/SlotTable$Companion; in class Landroidx/compose/runtime/SlotTable; or its superclasses (declaration of 'androidx.compose.runtime.SlotTable' appears in .. ```

i tried using Alpha05, Alpha06 and Alpha07 compose version along with the latest 
0.3.3.1 of accompanist

**Comment by chrisbanes** [comment]
This error is usually because you're using a dependency which is using an older version of Compose. Check `./gradlew app:dependencies`.

**Comment by ciscorucinski** [comment]
Same with `java.lang.NoSuchMethodError`. Make sure the version is not old
