### ISSUE TITLE
CoilImage: AnimatedVectorDrawable is not working for Android 10 and above

### ISSUE THREAD

**Issue by kameshyadavky** [chrisbanes/accompanist#144]
CoilImage is not able to animate AVDs for Android 10 and 11 but working fine for lower android versions.

**Comment by chrisbanes** [comment]
A couple of questions:

1) Can you include some sample code of what you're doing?

2) Why are you using `CoilImage` to load a drawable?

**Comment by kameshyadavky** [comment]
I am directly loading drawable into CoiIImage


```
CoilImage(
    data = R.drawable.avd 
) 
```


This was not my original intention but I am not able to load AVD in any way. So I tried to figure out what CoilImage is doing for loading AnimatedDrawable.

**Comment by chrisbanes** [comment]
AVDs aren't supported directly in Compose yet. 

What you're doing may by accident work on certain API levels, but isn't a supported use case.

I recommend that you look at this, to wrap a Drawable in a Painter: https://gist.github.com/chrisbanes/9a1d64847278876186be81249d9f9eda
