### ISSUE TITLE
Avoid Auto-Rotation Behavior (coil-image)

### ISSUE THREAD

**Issue by RobertMenke** [chrisbanes/accompanist#145]
Hey, I have a common workflow where a user takes a picture, and then that picture is used as the avatar photo for their profile. Currently, if I take a selfie with the phone positioned vertically the image is automatically rotated. The component I'm using for the avatar is as follows:

```kotlin
@Composable
fun ImageAvatar(bitmap: Bitmap, onClick: (() -> Unit)? = null) {
    var modifier = Modifier
        .preferredSize(70.dp)
        .clip(CircleShape)
        .background(backgroundSecondary())
        .border(BorderStroke(1.dp, backgroundPrimary()), shape = CircleShape)

    onClick?.let { clickListener ->
        modifier = modifier.clickable(onClick = clickListener)
    }

    Box(modifier = modifier, alignment = Alignment.Center) {
        CoilImage(
            data = bitmap,
            contentScale = ContentScale.Crop,
            requestBuilder = {
                transformations(CircleCropTransformation())
            },
            modifier = Modifier.preferredSize(70.dp)
        )
    }
}
```

Is there a way to avoid automatic rotation behavior?

**Comment by chrisbanes** [comment]
I'm confused. Why are you passing a bitmap into `CoilImage`?

You ready have the bitmap, so you just need to convert it to an `ImageAsset` via `asImageAsset()`, and display it directly via a normal `Image`.

**Comment by RobertMenke** [comment]
Well that's embarrassing, I didn't know Bitmap has a `asImageAsset` method 😅 . Confirmed this works and confirmed it's the bitmap itself that's rotated. Sorry for the spam!
