### ISSUE TITLE
dokka API generation seems broken

### ISSUE THREAD

**Issue by alexjlockwood** [chrisbanes/accompanist#154]
I noticed that there were a few issues with the dokka generation. For example in this file: https://chrisbanes.github.io/accompanist/api/insets/dev.chrisbanes.accompanist.insets/navigation-bars-height/

A couple things to note:

- Seems like the links to Compose APIs are broken (i.e. `Dp` is not getting recognized as a link to external Compose docs)
- Also seems like sample code is not getting properly formatted using markdown codeblocks.

**Comment by chrisbanes** [comment]
Yeah known issue. I've got a WIP PR #151 which should improve things.

**Comment by chrisbanes** [comment]
This should be fixed when we next push the docs at the next release.
