### ISSUE TITLE
ime paddings too big

### ISSUE THREAD

**Issue by AdrianoCelentano** [chrisbanes/accompanist#162]
I try to use the animated ime padding values for my animation, but the values seem too big for me. I might use it wrong.
```
class MainActivity : AppCompatActivity() {

    @ExperimentalAnimatedInsets
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        WindowCompat.setDecorFitsSystemWindows(window, false)

        setContent {
            ProvideWindowInsets(windowInsetsAnimationsEnabled = true) {
                Box(Modifier.fillMaxSize()) {
                    TextField(
                        value = "",
                        onValueChange = {},
                        modifier = Modifier
                            .align(Alignment.BottomCenter)
                            .navigationBarsPadding()
                            .padding(bottom = AmbientWindowInsets.current.ime.bottom.dp)
                    )
                }
            }
        }
    }
}
```

![Bildschirmfoto 2020-12-06 um 12 02 05](https://user-images.githubusercontent.com/1528394/101278330-e926a200-37ba-11eb-901a-a068c638c145.png)

![ime](https://user-images.githubusercontent.com/1528394/101278288-abc21480-37ba-11eb-8680-2c022c3fb981.gif)

**Comment by AdrianoCelentano** [comment]
i realized its in pixels and not in db 🙈

**Comment by chrisbanes** [comment]
Yep!

Any reason why you're doing it manually rather than using the provided modifiers? (`ime()` does exactly what you want, in a more optimal way)
