### ISSUE TITLE
CoilImage cannot display heif/heic images

### ISSUE THREAD

**Issue by sjmueller** [chrisbanes/accompanist#169]
When trying to display a heif/heic image via `CoilImage` using a remote url (example https://blink-content.s3.amazonaws.com/116ecc2a-4069-4365-afbf-ebb94ddb8d6b.heic), the image is not displayed and an error appears in the console:
```
E/HeifDecoderImpl: getSize: not supported!
```
The code that throws is likely here https://android.googlesource.com/platform/frameworks/av/+/android-8.1.0_r1/media/libheif/HeifDecoderImpl.cpp#258

Is there a way to use `CoilImage` such that heif decoding works as expected?

**Comment by chrisbanes** [comment]
This is a question to ask on the [Coil bug tracker](https://github.com/coil-kt/coil). Sounds like the bitmap has been recycled, but I haven't actually tried using HEIF on Android yet.

**Comment by sjmueller** [comment]
I have added the issue to their bug tracker coil-kt/coil/issues/619

**Comment by chrisbanes** [comment]
Closing this, as it looks like an issue in Coil's dependencies.
