### ISSUE TITLE
When many images are loaded from the remote URL and displayed to LazyColumnForIndexed, there will be a stutter problem when sliding. 

### ISSUE THREAD

**Issue by Merpyzf** [chrisbanes/accompanist#171]
When many images are loaded from the remote URL and displayed to LazyColumnForIndexed, there will be a stutter problem when sliding. A remote image loading component that I simply implemented by myself also has similar problems, but my implementation is implemented through onCommit().

running result: 

![](https://blog-1252413502.cos.ap-shanghai.myqcloud.com/Video_20201222_111434_667.gif)

my code: 

```
@Composable
fun App(){
    Surface(color = MaterialTheme.colors.background) {
        LazyGridFor(items = getImages(), rowSize = 4) {
            CoilImage(data = it)
        }
    }
}

@Composable
fun <T> LazyGridFor(
    items: List<T>,
    rowSize: Int = 1,
    itemContent: @Composable BoxScope.(T) -> Unit
) {
    val rows = items.chunked(rowSize)
    LazyColumnForIndexed(rows) { index, row ->
        Row(Modifier.fillParentMaxWidth(1f)) {
            for ((index, item) in row.withIndex()) {
                Box(Modifier.fillMaxWidth(1f / (rowSize - index))) {
                    itemContent(item)
                }
            }
        }
    }
}
```

Thank you for your contribution！👍

**Comment by chrisbanes** [comment]
This isn't a big tracker for Compose 😀.

Compose is in alpha so performance isn't expected to be perfect. If you find performance issues, please raise them on the Android bug tracker: https://issuetracker.google.com
