### ISSUE TITLE
Add contentDescription argument to GlideImage, PicassoImage, etc.

### ISSUE THREAD

**Issue by alexjlockwood** [chrisbanes/accompanist#183]
In 1.0.0-alpha11, `Image` was updated to take a `contentDescription: String?` argument.

Would be nice if these APIs were updated to be the same for consistency.

**Comment by chrisbanes** [comment]
Sounds good to me. I wonder if we need to think about adding some way to provide a different `contentDescription` for each loaded image. i.e: the param could be `(data) -> String?`

WDYT @JolandaVerhoef ?

**Comment by JolandaVerhoef** [comment]
I agree. If the visual element has semantic meaning, that meaning is probably changing depending on the image you're loading.

I do wonder how often we expect an asynchronously loaded image to actually have semantic meaning, and thus require a content description. We could consider defaulting this parameter to an empty lambda, so consumers only have to define it when their data actually contains a content description.

**Comment by chrisbanes** [comment]
Thinking about this a little more, maybe a normal String parameter is better.

If devs need to change it, they can use a `mutableStateOf` for the value.

**Comment by chrisbanes** [comment]
This was fixed in #184
