### ISSUE TITLE
[bug] Using accompanist-insets with FragmentContainerView doesn't trigger IME insets on first run

### ISSUE THREAD

**Issue by Kshitij09** [chrisbanes/accompanist#185]
I'm using `accompanist-insets` with a Fragment being hosted inside `FragmentContainerView`.  I tried using vanilla `ProvideWindowInsets` as well as `ViewWindowInsetObserver` but I'm getting same behaviour in both the cases.

I've also prepared a [repro](https://github.com/Kshitij09/compose-IME-glitch) for your reference. Kindly have a look at it as it's pretty severe issue for us.

Thanks!

**Comment by chrisbanes** [comment]
Thanks, what device and API level is being used for the repro?

**Comment by Kshitij09** [comment]
Device: Samsung M30s
Model Number: SM-M307F/DS
API Level: 30 (Android 10)

I've also observed this behaviour on Lenovo Tablet running android Marshmallow (6.0)

**Comment by Kshitij09** [comment]
Interesting insight! even if I don't provide windowInsets to `AmbientWindowInsets`, the behaviour remains same. Seems like AmbientWindowInsets have no effect at all.

**Comment by Kshitij09** [comment]
Found something! using `ViewWindowInsetsObserver` to provide insets and adding `navigationBarsWithImePadding()` modifier to root Composable solves the issue.

**Comment by chrisbanes** [comment]
I just tried your sample on the API 30 emulator and it works as expected, which makes me think this is a Samsung issue of some kind.

> Important: This also needs android:windowSoftInputMode="adjustResize" set for corresponding activity

Yep, documented [here](https://chrisbanes.github.io/accompanist/insets/#something-not-working)

> But this applies insets everytime a keyboard is opened. Is this expected behaviour? or we should only apply window insets if that TextField is getting hidden by the Keyboard?

Not sure what you mean here. If you're using `navigationBarsWithImePadding()` and the component is still being hidden by the IME, your layout probably needs to be tweaked to enable it to expand/collapse. Got an example?

**Comment by Kshitij09** [comment]
So what I meant is, `navigationBarsWithImePadding()` shifts the entire screen when keyboard is opened. Shouldn't it shift only so that TextField is visible? Like let buttons below TextField stay hidden just make TextField visible, or this is not how insets work? Also, do I need to use `navigationBarsWithImePadding()` this modifier for IME insets to work or it'll work implicity, IE shift screen whenever keyboard opens up?

**Comment by Kshitij09** [comment]
What do you mean by expected behaviour? insets are triggered on first run?

**Comment by chrisbanes** [comment]
> What do you mean by expected behaviour? insets are triggered on first run?

I mean, the sample you provided works fine on the API 30 emulator.  What do you mean by first run? First run of the app? Or the first opening of the IME after the device boots?

> So what I meant is, navigationBarsWithImePadding() shifts the entire screen when keyboard is opened. Shouldn't it shift only so that TextField is visible? Like let buttons below TextField stay hidden just make TextField visible, or this is not how insets work?

What you do with the layout is up to you. `navigationBarsWithImePadding()` isn't magic, it literally just adds padding to match whatever is greater out of the nav bars and IME. How you structure your layout to handle that, is your decision. If you want to move just the single component (as you described), you should move that view into a root `Box` to have it float above the rest of the content.

> Also, do I need to use navigationBarsWithImePadding() this modifier for IME insets to work or it'll work implicity, IE shift screen whenever keyboard opens up?

This is controlled by the `android:windowSoftInputMode` value. `adjustResize` tells the system to send IME changes as insets, and _not_ by automatically panning/shifting the window (which is `adjustPan`).

**Comment by Kshitij09** [comment]
So panning/shifting will work automatically if I remove `android:windowSoftInputMode="adjustResize"` and use only `ProvideWindowInsets { }` at the root of view? 

By first run, I meant first opening of IME. If you look at the Gif, the shifting/panning happens when the IME is opened for the second time and not the first time.

**Comment by chrisbanes** [comment]
> By first run, I meant first opening of IME. If you look at the Gif, the shifting/panning happens when the IME is opened for the second time and not the first time.

I doubt very much that this is something we can workaround in this library tbh. Sounds like a timing issue in the system/framework.

**Comment by Kshitij09-ag** [comment]
@chrisbanes any updates on this? what I might be doing wrong or any fixes you planned for this issue?

**Comment by chrisbanes** [comment]
I've already left the update above. There's nothing to fix as I can't reproduce it.

**Comment by Kshitij09-ag** [comment]
what was the behaviour you observed? I'll also try to run it on API 30 emulator but what is the expected behaviour here? panning should happen every time we focus a TextField which is getting hidden by the Keyboard?
