### ISSUE TITLE
Loading thumbnails for videos in device gallery

### ISSUE THREAD

**Issue by Jeyhey** [chrisbanes/accompanist#197]
Hi, first thank you for this great library. I use it for displaying images loaded via network as well as for pictures of the device gallery.

Now I want to display thumbnails of videos of the device gallery. To do so, I fetch the list of the video-Uri, and was thinking to pass that uri to CoilImage like so:

```
CoilImage(
    data = assetUri,
    contentDescription = null,
    contentScale = ContentScale.Crop,
)
```

This obviously does not work and no image is displayed. So I use a utility method to fetch a thumbnail bitmap of the uri and pass that bitmap to CoilImage, like so:

```
CoilImage(
    data = assetUri.thumbnailFromVideoAt(context, 0L)!!,
    contentDescription = null,
    contentScale = ContentScale.Crop,
)
```

with
```
fun Uri.thumbnailFromVideoAt(context: Context, timeMs: Long): Bitmap? {
    val retriever = MediaMetadataRetriever()
    retriever.setDataSource(context, this)
    retriever.getFrameAtTime(timeMs * 1000)
}
```

This works, but it fetches the bitmap on the main thread and thus my image grid is very laggy.

I was wondering if there was a better solution. I'm currently looking how to use directly `ImageLoad`.

Thank you for your help.

**Comment by chrisbanes** [comment]
Hmmm, do you're not really using Coil here at all, as you're just displaying a `Bitmap`. You could replace `CoilImage` with `Image` and it would work the same.

You should look at our [Asynchronous operations in Compose](https://developer.android.com/jetpack/compose/interop#async) doc to get an idea of how to do this (specifically the bit about `LaunchedEffect`)

**Comment by Jeyhey** [comment]
Hi Chris, thank you for your rapid reply. Indeed, I was thinking about using Image directly. Because I have a very large grid displaying thumbnails of all videos of the device, I thought using the build in caching and asynchronous loading of CoilImage instead of writing it myself. Also, because CoilImage can be used to display the _images_ of the device, I thought I can use it to display video thumbnails.

I'll take a look at your links and think about how implementing it using Image.

**Comment by chrisbanes** [comment]
Ah, turns out that Coil has support for this: https://coil-kt.github.io/coil/videos/

I haven't tried this, but it should then work as:

``` kotlin
CoilImage(
    data = videoUri,
    requestBuilder = {
        videoFrameMillis(1000)
    },
    contentScale = ContentScale.Crop,
)
```

**Comment by Jeyhey** [comment]
Thank you, this perfectly solves my problem. I only had to write my own `VideoFrameUriFetcher` to always return true in `handles` as the uri's last path segment does not indicate that it is a video (uri.toString() looks rather like this: 'content://media/external/video/media/15383').
