### ISSUE TITLE
White background colour

### ISSUE THREAD

**Issue by Jeyhey** [chrisbanes/accompanist#214]
When the image is loaded (ImageLoadState.Success clause), the background appears in a white colour for about a second before the image is set. This happens although the background is set through the modifier to another colour.

To better reproduce you can set your device to dark mode and the background of the CoilImage to black via modifier.

This issue started appearing in version 0.6.0 and not before.

(On this note, I also wonder why there is this delay of about one second. Why isn't the image shown directly after it is loaded?)

**Comment by chrisbanes** [comment]
Thanks for the report. Sounds like this might be caused by #206. I'll take a look

**Comment by chrisbanes** [comment]
Actually #213 wasn't in v0.6.0, and that fixes the issue. I'll release a v0.6.1 now containing that.
