### ISSUE TITLE
Images are not exposed when the combination of AndroidView + FrameLayout + Fragment

### ISSUE THREAD

**Issue by Pluu** [chrisbanes/accompanist#215]
When using fragments in accompanist's image loader and Composable, the behavior is incorrect at the first display.

Condition

1. AndroidView + FrameLayout + Fragment combination
2. Use accompanist's image loader inside Fragment

If you touch the Composable View, it is exposed.

Sample : https://github.com/Pluu/MaybeComposeBug

Sorry. It is not clear if it is a Compose issue, but only accompanist works differently, so I registered the issue here.

**Comment by chrisbanes** [comment]
Fragments in `AndroidView` are currently quite buggy: https://issuetracker.google.com/issues/179915946

I doubt that this is an Accompanist bug. I'll close this for now
