### ISSUE TITLE
Cannot resolve snapshots

### ISSUE THREAD

**Issue by JohannBlake** [chrisbanes/accompanist#216]
I followed your instructions on how to use the latest snapshots but was unsuccessful. My project gradle file includes the following:

    repositories {
        google()
        mavenCentral()
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
    }

I then added these dependencies:

```
dependencies {
    classpath 'dev.chrisbanes.accompanist:accompanist-coil:0.6.2-SNAPSHOT'
    classpath 'dev.chrisbanes.accompanist:accompanist-imageloading-core:0.6.2-SNAPSHOT'
    classpath 'dev.chrisbanes.accompanist:accompanist-insets:0.6.2-SNAPSHOT'
    classpath 'dev.chrisbanes.accompanist:accompanist-mdc-theme:0.1.6.ui-6602655-SNAPSHOT'
}
```

This results in the error of:

> Could not resolve dev.chrisbanes.accompanist:accompanist-coil:0.6.2-SNAPSHOT.

I then attempted to move the dependencies to the app's gradle file and used this:

```
dependencies {
    implementation 'dev.chrisbanes.accompanist:accompanist-coil:0.6.2-SNAPSHOT'
    implementation 'dev.chrisbanes.accompanist:accompanist-imageloading-core:0.6.2-SNAPSHOT'
    implementation 'dev.chrisbanes.accompanist:accompanist-insets:0.6.2-SNAPSHOT'
    implementation 'dev.chrisbanes.accompanist:accompanist-mdc-theme:0.1.6.ui-6602655-SNAPSHOT'
}
```

This results in the errors:

> Failed to resolve: dev.chrisbanes.accompanist:accompanist-imageloading-core:0.6.2-SNAPSHOT
> Failed to resolve: dev.chrisbanes.accompanist:accompanist-insets:0.6.2-SNAPSHOT
> Failed to resolve: dev.chrisbanes.accompanist:accompanist-coil:0.6.2-SNAPSHOT

Those snapshots do in fact exist at the locations specified, so I have no idea why they can't be found.

Personally, I find it a shame that Google's Android team has referenced this library as their main library for handling images. Like WTF?? I get it that Compose is still in beta, but seriously, to release a beta with zero native support for images for Android is just plain idiotic.

**Comment by chrisbanes** [comment]
> Personally, I find it a shame that Google's Android team has referenced this library as their main library for handling images. Like WTF?? I get it that Compose is still in beta, but seriously, to release a beta with zero native support for images for Android is just plain idiotic.

I don't respond to comments like this. Closing.
