### ISSUE TITLE
[API Request] Flag/param to display current image while loading replacement image

### ISSUE THREAD

**Issue by aconda-mercari** [chrisbanes/accompanist#221]
My use case is a common one:

In an ImageList/Detail UX,
  Display an already available and cached thumbnail-resolution photo while loading the higher-resolution photo,
in order to provide a seamless load of the photo.

Currently, loading state will always happen in between when this [function](https://github.com/chrisbanes/accompanist/blob/69aa0e67d1883e05038260cd854c5f9ed731b503/glide/src/main/java/dev/chrisbanes/accompanist/glide/GlideImage.kt#L174-L213) is used.

I think I could use the other overload to achieve this, but the overload linked above is super convenient with the extra parameters and the MaterialLoadingImage already implemented.

So I was wondering if we could consider adding an API for this at the same level as the other convenience properties such as `fadeIn`.

**Comment by chrisbanes** [comment]
As you saw, this is a good job for the overload function. I don't really want to add more implicit functionality to the 'slot' functions as they're already getting too big.
