### ISSUE TITLE
Error Composable flashes while loading CoilImage

### ISSUE THREAD

**Issue by lwis** [chrisbanes/accompanist#228]
## Describe the bug
During loading the provided error content flashes - unfortunately struggling to work out if it's displayed before or after the loading animation (I think after).

## To Reproduce
```
CoilImage(
        data = imageUrl,
        contentDescription = null,
        loading = {
            Box(contentAlignment = Alignment.Center) {
                CircularProgressIndicator()
            }
        },
        error = {
            Box(contentAlignment = Alignment.Center) {
                Icon(imageVector = Icons.Filled.ErrorOutline, contentDescription = null)
            }
        },
    )
```

## Expected behavior
Loading, then image to be displayed.

## Screenshots?
I'll try to record if helpful.

## Environment:
 - Android OS version: 11
 - Device: Pixel 5
 - Accompanist version: v0.6.1
 - Latest Compose/AndroidX releases.

**Comment by chrisbanes** [comment]
Thanks for the report. This is the same as #217.

You can try out the snapshots if you need a fixed build.
