### ISSUE TITLE
How can I use a .gif when is a local resource

### ISSUE THREAD

**Issue by yotislenny** [chrisbanes/accompanist#231]
Usually with glide is possible to use .gif it works with an URL but it doesn’t work when the .gif is a resource
example

 GlideApp.with(context).asGif().load(setImageResource(R.drawable.giphy))

how can I do that using accompanist

something like ....

GlideImage(
            data = setImageResource(R.drawable.giphy)
        )

is that even possible ? 

sorry I'm new in android trying to learn to use compose...
thank you for your awesome library btw!

**Comment by chrisbanes** [comment]
The following should work:

```
GlideImage(
  data = R.drawable.giphy
)
```
