### ISSUE TITLE
RoundedCornerShape on CoilImage affects only 2 bottom corners

### ISSUE THREAD

**Issue by arnis71** [chrisbanes/accompanist#75]
I use CoilImage like this
```
CoilImageWithCrossfade(
          data = it,
          getFailurePainter = { ColorPainter(Color.Red) }
          contentScale = ContentScale.FillWidth,
          modifier = Modifier.clip(RoundedCornerShape(10.dp)).fillMaxWidth().padding(top = 8.dp)
)
```
And result is the following:
![Screenshot_1600011190](https://user-images.githubusercontent.com/19541486/93022107-9052cd80-f600-11ea-8464-2df946f26619.png)

The top corners are not affected. I tried the same thing on the `Box` composable and it works so it is not a compose issue. It also works with `CircleShape` clipping so I guess it is some issue with `RoundedCornerShape` clipping for images. Does this needs a fix or am I doing something wrong?

**Comment by chrisbanes** [comment]
This is due to your modifier order. You want instead:

``` kotlin
modifier = Modifier
    .padding(top = 8.dp) // This should be the last applied, since it's basically a margin
    .clip(RoundedCornerShape(10.dp))
    .fillMaxWidth()
```

Note: the same thing happens with `Image`
