### ISSUE TITLE
DrawShadow causes weird boxing of some images

### ISSUE THREAD

**Issue by gastsail** [chrisbanes/accompanist#84]
I have integrated CoilImage, so far its awesome! Thanks for your time into this extension

I have a problem when I try to add a back shadow to each image, it seems like for some images it renders ok the shadow with the elevation, but for some others it's likely to draw the shadow ok but the image inside is placed in a diamond fashion

Maybe is an error on my side, but is weird that some images are loaded ok and the others like this

![Captura de pantalla 2020-09-17 a la(s) 10 41 59](https://user-images.githubusercontent.com/24615408/93479805-20c83100-f8d3-11ea-8459-424028e46902.png)

**Code**

```
@Composable
private fun UserRow(user:User,onUserClick: (User) -> Unit) {
    Row(modifier = Modifier.clickable(onClick = { onUserClick(user) }).fillMaxWidth().padding(8.dp)) {
        val imageModifier = Modifier.preferredSize(46.dp).drawShadow(elevation = 4.dp, shape = CircleShape)
        CoilImage(data = user.profilePicutre,modifier = imageModifier,contentScale = ContentScale.Crop)
        Column (modifier = Modifier.padding(start = 8.dp).align(Alignment.CenterVertically)){
            Text(text = user.name, fontWeight = FontWeight.Bold, style = MaterialTheme.typography.h6)
            ProvideEmphasis(EmphasisAmbient.current.medium) {
                Text(text = user.bio,style = MaterialTheme.typography.body2)
            }

        }
    }
}
```

**Comment by chrisbanes** [comment]
This isn't an issue in Accompanist. I'm guessing that the images have a transparent background, so you're seeing the shadow implementation behind it. I recommend adding a white background:

```
Modifier.preferredSize(46.dp)
    .drawShadow(elevation = 4.dp, shape = CircleShape)
    .background(color = Color.White, shape = CircleShape)
```

...or just use a `Surface` wrapper.
