### ISSUE TITLE
Add @Composable placeholder for errors

### ISSUE THREAD

**Issue by bvitaliyg** [chrisbanes/accompanist#86]
Something like:
`error: @Composable ((ErrorResult) -> Unit)? = null`

The reason is that you might be needed to display a custom placeholder if the load fails. The might not be a regular image as you might be needed to use some logic there (showing differect vectors assets, drawing checkmarks etc).

**Comment by chrisbanes** [comment]
I am actually thinking of converting `getSuccessPainter` and `getFailurePainter` to simply:

```
fun CoilImage(
    image: @Composable ((SuccessResult) -> Unit) = { Image(it.image) },
    error: @Composable ((ErrorResult) -> Unit)? = null,
) {
```

This would also simplify the crossfade implementation. Sounds like this would work?

**Comment by chrisbanes** [comment]
Could even simplify it further to:

```
fun CoilImage(
    image: @Composable ((RequestResult) -> Unit) = { 
        if (it is SuccessResult) {
            Image(it.image)
        }
    }
)
```

**Comment by bvitaliyg** [comment]
This looks very nice!
