### ISSUE TITLE
API update proposal

### ISSUE THREAD

**Issue by bvitaliyg** [chrisbanes/accompanist#92]
With the recent update we have 3 callback for each situation, such as:

- Image is loading
- Image is loaded
- Image has failed to load.

We also have an internal sealed class `RequestResult` which represents the state of the loader. When the image is loading, the internal code uses `null` instead.

My suggestion is:
- Make it public and rename to something like `CoilState` or `CoilImage`.
- Move all the children classes inside parent for more code clarity, rename it to `Success` and `Fail`.
- Add third state, `object Loading: CoilState()`, and use it instead of nulls, in a similar way Compose does for a lot of components, for example `Modifier`.
- Move nullable `image` property from sealed class to success state, and make it not null.
- Add a single trailing lambda for all the states, e.g. `content: @Composable (CoilState) -> Unit`. This will allow to use syntax like `CoilImage(url){ it: CoilState -> }` with `when` expression inside – it's more easy and consistent rather than using 3 lambdas.
- Add an overload with the lambdas for other cases.

It'd be great to see `CoilImage()` as a state managing function, completely without rendering logic. Overloads with the current functionality may still be available as well.

It'd be interesting to hear more opinions from the community as well.

**Comment by chrisbanes** [comment]
Thanks for the suggestions. I agree on all of the points you've made, and they should all be covered in #93
